address: 127.0.0.1
port: 9091
baseURL: /filebrowser

database: /var/lib/filebrowser/main.db
root: /
log: stdout

# auth.header: Remote-User
# auth.method: proxy
auth.method: noauth
signup: false

branding.disableExternal: true
