address: 0.0.0.0
port: 9091
baseURL: /filebrowser

database: /var/lib/filebrowser/main.db
root: /
log: stdout

signup: false

auth:
  header: Remote-User
  method: proxy

branding:
  disableExternal: true
