name: Feature Request
description: Suggest an idea or improvement
labels: [ 'enhancement' ]
body:
  - type: textarea
    attributes:
      label: Feature Description
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Suggested Solution
      description: List any ideas you have for how to implement this feature.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional Context
      description: Any extra information that might help us investigate.
