FROM docker.io/privatebin/fs:{{ plugin.custom.privatebin_version }}
USER root
COPY config/conf.php /etc/privatebin/conf.php
COPY config/site.conf /etc/nginx/http.d/site.conf
RUN apk add --no-cache libcap && \
    setcap 'cap_net_bind_service=+ep' /usr/sbin/nginx && \
    chown nobody:www-data /etc/privatebin/conf.php && \
    chmod 644 /etc/nginx/http.d/site.conf
