{% set NODE_VER = '20.9.0-alpine' %}

FROM docker.io/library/node:{{ NODE_VER }} AS builder
WORKDIR /app
COPY package*.json .
RUN npm ci
COPY . .
RUN npm run build
RUN npm prune --production

FROM docker.io/library/node:{{ NODE_VER }}
WORKDIR /app
COPY --from=builder /app/build build/
COPY --from=builder /app/node_modules node_modules/
COPY package.json .
