{% set NODE_VER = '20.10.0-alpine' %}

FROM docker.io/library/node:{{ NODE_VER }} AS builder
WORKDIR /app
COPY package.json pnpm-lock.yaml .
RUN corepack enable && pnpm install --frozen-lockfile
COPY . .
RUN pnpm run build && pnpm prune --prod

FROM docker.io/library/node:{{ NODE_VER }}
WORKDIR /app
COPY --from=builder /app/build build/
COPY --from=builder /app/node_modules node_modules/
COPY package.json .
