FROM docker.io/jupyterhub/jupyterhub:{{ plugin.custom.jupyterhub_version }}
RUN python3 -m pip install --no-cache-dir --upgrade setuptools pip && \
    python3 -m pip install --no-cache-dir 'jupyterlab=={{ plugin.custom.jupyterlab_version }}' && \
    {% for account in users.accounts %}
        {% if account.role == 'admin' %}
    useradd --no-log-init -g root -G sudo -m -s /usr/bin/bash '{{ account.username }}' && \
        {% else %}
    useradd --no-log-init -g root -m -s /usr/bin/bash '{{ account.username }}' && \
        {% endif %}
    echo '{{ account.username }}:{{ plugin.custom.jupyterhub_password }}' | chpasswd && \
    ln -s '/mnt/home/{{ account.username }}' '/home/{{ account.username }}/home' && \
        {% for shared_dir in account.extra.shared_dirs %}
    ln -s '/mnt/{{ shared_dir.name }}' '/home/{{ account.username }}/{{ shared_dir.name }}' && \
        {% endfor %}
        {% for shared_dir in config.directories.shared_dirs %}
    ln -s '/mnt/{{ shared_dir.name }}' '/home/{{ account.username }}/{{ shared_dir.name }}' && \
        {% endfor %}
    {% endfor %}
    :
