name: Release

on:
  push:
    branches:
      - main
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  gh-release:
    name: Create GitHub release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Get changelog
        id: changelog
        run: |
          {
            echo 'changelog<<EOF'
            sed '/^## \['${GITHUB_REF_NAME#v}'\].*$/,/^## /!d;//d;/./,$!d' CHANGELOG.md
            echo 'EOF'
          } >> "$GITHUB_OUTPUT"

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          body: ${{ steps.changelog.outputs.changelog }}
          makeLatest: true

  pypi-release:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build package
        run: python -m build

      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
