import { env } from "$env/dynamic/public"

export const HOSTNAME = env.PUBLIC_HOSTNAME
export const HTTPS_PORT = env.PUBLIC_HTTPS_PORT
export const SITE_SUBTITLE = env.PUBLIC_SITE_SUBTITLE
export const SITE_TITLE = env.PUBLIC_SITE_TITLE
export const XRAY_DOMAIN_WHITELIST = env.PUBLIC_XRAY_DOMAIN_WHITELIST
export const XRAY_DOMAIN_KEYWORD_WHITELIST = env.PUBLIC_XRAY_DOMAIN_KEYWORD_WHITELIST
export const XRAY_DOMAIN_SUFFIX_WHITELIST = env.PUBLIC_XRAY_DOMAIN_SUFFIX_WHITELIST
export const XRAY_IP_RANGE_WHITELIST = env.PUBLIC_XRAY_IP_RANGE_WHITELIST
